#!/bin/bash

version=`grep -m 1 'version := ' bsnes/Makefile | awk '{ print $3 }'`;
bsnes_version=bsnes_${version}
dist_dir=distribution

#clean & set up distribution directory
rm -f ${dist_dir}/${bsnes_version}.zip
rm -frd ${dist_dir}/${bsnes_version}
mkdir -pv ${dist_dir}/${bsnes_version}
cp -a bsnes/data/bsxdat ${dist_dir}/${bsnes_version}/bsxdat

#build compatibility app bundle
cd bsnes
make clean
make -j4 distribution profile=compatibility
cd ..
mv ./bsnes+.app ${dist_dir}/${bsnes_version}/bsnes+.app

#build accuracy app bundle
cd bsnes
make clean
make -j4 distribution profile=accuracy
cd ..
mv ./bsnes+accuracy.app ${dist_dir}/${bsnes_version}/bsnes+accuracy.app

#zip distribution directory
pushd ${dist_dir}
zip -9 -r ${bsnes_version}.zip ${bsnes_version}
popd
